[phases.setup]
nixPkgs = ["flutter", "git", "nodejs"]

[phases.install]
cmds = ["flutter pub get"]

[phases.build]
cmds = ["bash -c \"flutter build web --release --web-renderer canvaskit --dart-define=API_BASE_URL=${API_BASE_URL:-http://localhost:8000}\""]

[start]
cmd = "npx serve -s build/web -p ${PORT:-8000}"
